openapi: 3.0.0
info:
  title: Todo AI Chatbot API
  version: 1.0.0
paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI chatbot
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                conversation_id:
                  type: string
                  format: uuid
              required:
                - message
      responses:
        '200':
          description: Assistant response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  conversation_id:
                    type: string
                    format: uuid
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
